name = "__WORKER_NAME__"
account_id = "__ACCOUNT_ID__"
main = ".output/server/index.mjs"
compatibility_date = "2025-09-28"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".output/public"
binding = "ASSETS"

