name: Deploy to Cloudflare (Release)
on:
  release:
    types:
      - released
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
        default: 'v0.0.0'
concurrency:
  group: cloudflare-worker-prod
  cancel-in-progress: false
permissions:
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.event_name == 'pull_request' && github.head_ref || github.event.release.tag_name || github.sha }}
      NODE_ENV: production
      NITRO_PRESET: cloudflare_module
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
      - name: Install deps
        shell: bash
        run: pnpm i --frozen-lockfile
      - name: Build (Nuxt)
        shell: bash
        run: pnpm build
      - name: Deploy to Cloudflare Workers
        uses: Shion1305/cloudflare-worker-deploy@v1
        with:
          worker_name: shion-pro-release
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          account_id: 1ea2d4d3f13ac740bfb6be382649fd8a
